### ISSUE TITLE
[Bug] Another Crash because of minecord

### ISSUE THREAD

**Issue by Eatham532** [axieum/minecord#41] opened 2022-06-30 07:00 UTC
### Expected behavior

The server to start

### Observed/actual behavior

The server crashes

Crash log:
[crash-2022-06-30_16.58.33-server.txt](https://github.com/axieum/minecord/files/9017174/crash-2022-06-30_16.58.33-server.txt)

### Steps/models to reproduce

Add Minecord and make sure that all discord settings are correct.

### Version

1.0.0 beta 2

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

**Comment by axieum** [comment] 2022-07-01 01:53
Duplicate of #40

**Closed by axieum** 2022-07-01 01:53 UTC
